### ISSUE TITLE
No KATs published

### ISSUE THREAD

**Issue by Exaelitus** [avaneev/komihash#6]
I couldn't find any test vectors for komihash.

Could you please publish some so that I (and others) can verify implementations and ports are correct?

**Comment by Exaelitus** [comment]
I did see two of the Ports you linked in your docs have ONLY two test vectors ( "test1" and "test2" ) which are poor tests, and also do not agree on the resultant hash ( BIG problem ).

So official KATs are critical, IMHO.

**Comment by avaneev** [comment]
Thanks for the note. I've added test vectors to the project page, enjoy.
