### ISSUE TITLE
Is it safe to skip first round of komihash when performing discrete-incremental hashsing

### ISSUE THREAD

**Issue by thynson** [avaneev/komihash#9]
When doing discrete-incremental hashing, I feels that [first round](https://github.com/avaneev/komihash/blob/c4e03a39b146e8411a1c166b47758d4b250d7878/komihash.h#L649) of komihash can be skipped. Let's call it `komihash_inner`

```c
uint64_t komihash_inner(const void* const Msg0, size_t MsgLen,
        uint64_t *Seed1, uint64_t *Seed5  ) {
   //...
}
```

and `komihash` can become
```c
uint64_t komihash( const void* const Msg0, size_t MsgLen,
	const uint64_t UseSeed ) {
   	const uint8_t* Msg = (const uint8_t*) Msg0;

	// The seeds are initialized to the first mantissa bits of PI.

	uint64_t Seed1 = 0x243F6A8885A308D3 ^ ( UseSeed & 0x5555555555555555 );
	uint64_t Seed5 = 0x452821E638D01377 ^ ( UseSeed & 0xAAAAAAAAAAAAAAAA );
	uint64_t r1h, r2h;

	KOMIHASH_PREFETCH( Msg );

	KOMIHASH_HASHROUND(); // Required for Perlin Noise.
        komihash_inner(Msg0, MsgLen, &seed1, &seed5);
}
```

Then we can introduce `struct DescreteKomihash` and `komihash_discrete_hash`

```c
struct DescreteKomihash {
        uint64_t Seed1;
        uint64_t Seed5;
}

uint64_t komihash_discrete_hash(struct DescreteKomihash *d, const void* const Msg0, size_t MsgLen) {
        komihash_inner(Msg0, MsgLen, &d->seed1, &d->seed5);
        return d->seed1;
}
```

where `DescretKomihash` will be initialized with a seed with similar steps in `komihash`.

Such construct reduce a multiply operation for each call. 

But I don't have knowledge in how to design a good hash function, I have no idea if it's safe do it in this way. Any comment or advise?

**Comment by avaneev** [comment]
I do not think it's possible to opimize komihash that way, because one does not know input data lengths in advance - for example, one may been to hash 64 byte block, and not merely 4- or 8-byte blocks, so needs another initialization.
